### ISSUE TITLE
Yara rules missing

### ISSUE THREAD

**Issue by silascutler** [dsnezhkov/racketeer#1]
Are you planning to release Yara rules for enhanced blue team collaboration?

**Comment by silascutler** [comment]
Hey, great talk today. I put together a quick Yara rule, haven't fully tested but wanted to get what I could over as soon as possible.  I send an updated version on Monday or so and add in other detection rules.   

```
rule racketeer
{
	meta:
		author = "Silas Cutler"
		description = "Racketeer Ransomware detection based on Console.WriteLine calls"
		version = "0.1"
	strings:
		$ = "Exception: {0}" wide ascii
		$ = "Password Bytes: {0}" wide ascii
		$ = "CryptographicException error: " wide ascii
		$ = "Error by closing CryptoStream: " wide ascii
		$ = "Ex: {0} {1}" wide ascii
		$ = "Connecting to server ..." wide ascii
		$ = "Connected." wide ascii
		$ = "Client sends REQUEST of size {0}: Serialized as: {1}\n" wide ascii
		$ = "Send: IO exception {0}" wide ascii
		$ = "Client received RESPONSE: De-Serialized as: {0}\n" wide ascii
		$ = "Receive: IO exception {0}" wide ascii
		$ = "                Console.WriteLine($" wide ascii
	condition:
		8 of them	
}
```

**Comment by silascutler** [comment]
Visual studio finished updating and I was able to check verify the rule matches on a compiled copy of `FileConnector.exe` (rule was written based on the source code).

**Comment by dsnezhkov** [comment]
Thank you. I will close that for now and have it stay as an FYI as I have no plans to update it in the near future.
