### ISSUE TITLE
wildcards in the FilePath

### ISSUE THREAD

**Issue by wimdecorte** [dsnezhkov/racketeer#10]
Does the policy allow for wildcards to specify all files in a folder?
Specifying an individual file works
      "Files": [
        {
          "FilePath": "D:/live_files/OAuth_tester.fmp12",
          "Operation": 2,
          "Key": "9993c359-c68a-4c11-8cd0-f4c4695be28f"
        },

but using any of these does not
          "FilePath": "D:/live_files/",
          "FilePath": "D:/live_files/*",
          "FilePath": "D:/live_files/*.*",

**Comment by dsnezhkov** [comment]
Not yet supported but planning on doing so.
