### ISSUE TITLE
server null exception on processing second "File" entry

### ISSUE THREAD

**Issue by wimdecorte** [dsnezhkov/racketeer#11]
I'm working on a branch that will take a folder and iterate through the files in the folder for encrypting.
When the code processes the second array element in Files, it errors out:

From the log:

> 2021.11.09 08:21:41.125 Debug   Wrote salt 60-F2-81-E0-C3-2F-9D-A8-CB-71-04-B2-21-0D-5E-AB-AA-41-B4-40-B0-22-C2-61-12-88-89-81-69-3A-3F-C8 of size: 32
2021.11.09 08:21:41.141 Debug   Flushed final block
2021.11.09 08:21:41.141 Debug   Encryption routine success
2021.11.09 08:21:41.141 Debug   Deleting original file D:\fms_backups\FMS_2021-10-26_0000\live_files\OAuth_tester.fmp12
**2021.11.09 08:21:41.156 Debug   entry to process: D:\live_files\**
2021.11.09 08:21:41.156 Debug   folder detected: D:\live_files\
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\OAuth_tester.fmp12
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\SenseHat.fmp12
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\Soliant wstest.fmp12
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\sound_levels.fmp12
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\the_Data.fmp12
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\the_UI.fmp12
2021.11.09 08:21:41.156 Debug   file added: D:\live_files\xero.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\punisher\Punisher_20210301_FMbug.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\punisher\Punisher_20210306.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\punisher\Punisher_20210318_j.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\punisher\Punisher_small.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\punisher\Punisher_smaller.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\punisher\Punisher_test_data.fmp12
2021.11.09 08:21:41.172 Debug   file added: D:\live_files\RC_Data_FMS\mitsy_sandbox\mitsy_sandbox\video_file\21-03-29\15-04-40_feederbowls_135.mp4
2021.11.09 08:21:41.172 Debug   file collection process done, time to start processing, 14 files to process...
2021.11.09 08:21:41.172 Debug    processing file: D:\live_files\OAuth_tester.fmp12
2021.11.09 08:21:41.172 Debug
 Server may not be reachable

2021.11.09 08:21:41.187 Debug   Sleeping for 5000
2021.11.09 08:21:46.217 Debug   Response from base:{"siteId":"","taskName":"","taskType":0,"taskArgs":null,"taskB64Payload":""}

Line 6 (bolded) is where it starts on the second "Files" entry, it adds the files to the list and then when it is time to call Cryptor.cryptFileKickOff the server is not found anymore:

![image](https://user-images.githubusercontent.com/5022743/140945271-3c4453ff-bb57-49ca-90ce-15f7b95d8ce8.png)

It is not clear to me why that would be.  At that point the agent has only been processing for about 20 seconds.
Why is
 CheckTaskAsync().GetAwaiter().GetResult();
throwing a NullReferenceException at this point?

**Comment by dsnezhkov** [comment]
Can you check that the file is not in use? it may be trying to move the file with an open handle on it. I will need to do a check for it before the exception is handled by the server.

**Comment by wimdecorte** [comment]
Yes, file was in use; I've added code to detect that and skip the files.
