### ISSUE TITLE
go run main.go generates errors

### ISSUE THREAD

**Issue by wimdecorte** [dsnezhkov/racketeer#2]
checked out the code using gh, running  "go run main.go" 

ubuntu@ip-xxx-xxx-xxx-xxx:~/racketeer/server$ go run main.go
main.go:6:2: package RNS/serve is not in GOROOT (/usr/local/go/src/RNS/serve)
main.go:7:2: package RNS/types is not in GOROOT (/usr/local/go/src/RNS/types)

This is a plain vanilla Ubunti 18.04, nothing but Go on it (fresh instance for the purpose of testing - go1.17.1 linux/amd64).

VS Code also throws this error when inspecting the code, which seems to be related.

![image](https://user-images.githubusercontent.com/5022743/135322965-33a24c07-8601-44c2-80d2-fc07b7308f5d.png)

Folder structure (unmodified after checking out the code) of the server folder:

ubuntu@ip-172-31-57-127:~/racketeer/server$ tree .
.
├── dist
│   ├── gencert.sh
│   ├── server.crt
│   └── server.key
├── go.mod
├── keys
│   ├── server.crt
│   └── server.key
├── main.go
├── man
│   └── masterkey.template
└── src
    └── RNS
        ├── help
        │   ├── go.mod
        │   └── masterkey.go
        ├── routers
        │   ├── go.mod
        │   ├── go.sum
        │   └── router.go
        ├── serve
        │   ├── go.mod
        │   ├── go.sum
        │   ├── httpserver.go
        │   └── tuishell.go
        ├── surveys
        │   ├── clearlogs.go
        │   ├── execagent.go
        │   ├── getlogs.go
        │   ├── go.mod
        │   ├── go.sum
        │   ├── heartbeat.go
        │   ├── masterkey.go
        │   ├── polexec.go
        │   ├── setlogs.go
        │   ├── setlogsource.go
        │   └── summary.go
        ├── types
        │   ├── go.mod
        │   ├── help.go
        │   ├── model.go
        │   └── tui.go
        └── utils
            ├── go.mod
            └── util.go

**Comment by dsnezhkov** [comment]
Try this:

# Dev/Build
## Prerequisites:

- Reasonably latest Golang dist (16+)
- You should have export GOROOT pointing to GO SDK (e.g. /usr/local/go-17.1/).
- You should have export GOPATH pointing to where your Go workspace (e.g. /User/dev/go)
Compile code:

1. Clone the repo: `got clone <this repo path>`
2.Navigate to the server component: `cd racketeer/server`
3. Build the code: `GO111MODULE=on go build -o bin/server.exe`

**Comment by wimdecorte** [comment]
No joy.  See two screenshots below.  The instructions work and I've done the required "go gets" which led to a successful build but then an error on execution.

![image](https://user-images.githubusercontent.com/5022743/135689251-c6003bd8-c303-4588-9b40-8878603cbd62.png)

![image](https://user-images.githubusercontent.com/5022743/135689261-0bab8e57-13a6-482f-9e09-9a8c3402d70f.png)



Even when run the executable as sudo

![image](https://user-images.githubusercontent.com/5022743/135689228-a831666e-ca05-4172-8ee2-cd73b611805e.png)

**Comment by wimdecorte** [comment]
and just to confirm that there is nothing else listening on port 3000 (shouldn't be since this is a clean AWS instance)

![image](https://user-images.githubusercontent.com/5022743/135689483-259a9e21-a0f1-43da-8d61-42a6f7fb4314.png)

**Comment by wimdecorte** [comment]
and I'm a C# / JS guy with no experience whatsoever with Go, so don't feel bad about pointing out silly mistakes I'm making.

**Comment by dsnezhkov** [comment]
No worries. The documents are not clear as to how SSL keys are found. 

Run:

`$ server -H 127.0.0.1 -P 3001 -s `

This will start server on IP/Port with the TLS support.

Please make sure that there is a `keys` folder right next to the server executable which contains TLS certs. In the future there will be an option to point to correct directory with keys. Right now, it's a hardcoded assumption [here](https://github.com/dsnezhkov/racketeer/blob/587b0947564598e1976c874104dde815de3aa38a/server/serve/httpserver.go#L41) 

In the above example (launching `server` from `./bin` ) place certificates in `keys` directory inside `./bin`. Take a look at `./dist/gencert.sh` key generation script to get self-signed certs, or extract from Letsencrypt/etc. for the host/domain.
