### ISSUE TITLE
example of agent config file

### ISSUE THREAD

**Issue by wimdecorte** [dsnezhkov/racketeer#4]
It is not clear to me from the docs or from the source code, how the agent knows where the server is. I'm guessing you can specify that in the config file; is there a template agent config file you can add to the repo?

**Comment by dsnezhkov** [comment]
The agent can operate on the config file if you are launching it manually with the `-c ` or --cfg` flag. But often it can operate  off of the embedded resource as it is launched. See project file (https://github.com/dsnezhkov/racketeer/blob/053a12310a39822b35ddbb7f2e3b466fe8840902/agent/FileConnector/FileConnector.csproj#L128 ) . `policy-minimal-network.json` is the minimal file you want to modify to point to the C2. Specifically, you want to manage the `ExtEndpoints` directive in JSON file which will point to the server to connect to. 

The embedded file is can be modified and the agent "cut"  with initial configuration, possibly including predetermined targeted assets and authentication for scenarios when the agent does not want to reach to C2 for further policy load from the operator, but can immediately go to work on the provided policy. More extensive examples of what policy can include can be found in `agent/configs` folder.

Hope that helps.
