### ISSUE TITLE
License

### ISSUE THREAD

**Issue by billyjbryant** [dsnezhkov/racketeer#8]
I attended your talk @ DEFCON 29 and really enjoyed it. 
I like the project here but you do not have a license uploaded. My organization precludes using OSS in our environment unless it utilizes the MIT license. 

Could you please upload a license file so that I can validate whether or not I can utilize this in my environment?

**Comment by dsnezhkov** [comment]
Thank you! It should be already in the repo - [LICENSE](https://github.com/dsnezhkov/racketeer/blob/main/LICENSE) . Let me know if this works.

**Comment by billyjbryant** [comment]
Thank you, I see it! This works!

**Comment by billyjbryant** [comment]
And Sorry for creating a dupe issue, I forgot I had submitted the issue a few days ago!
